# Generated by Django 3.2.20 on 2023-09-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='friendly_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='yeargroup',
            name='friendly_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.book'),
        ),
    ]
