# Generated by Django 3.2.20 on 2023-09-28 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='inventory.subject'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='inventory.yeargroup'),
        ),
    ]
