# Generated by Django 3.2.20 on 2023-09-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_original_bag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_option',
            new_name='shipping_required',
        ),
    ]
