# Generated by Django 3.2.20 on 2023-09-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='stock_item',
            new_name='stock',
        ),
    ]
